/* GENERATED by functions/src/build-form.ts from the catalogue in functions/src/mamba/ — do not edit this file by hand.
 * The cohort calendar: the site's countdown and the application form read it;
 * the Firestore rules and the Cloud Function enforce the same deadlines. */
window.MVP_COHORTS = [
  {
    "n": 1,
    "starts": "2027-01-26",
    "startsAt": "2027-01-26T09:00:00+08:00",
    "startsLabel": "26 Jan 2027",
    "closesAt": 1800666000000
  }
];
